# Staging environment configuration
---
environment: staging

# Security settings for staging (more secure than dev)
consul_acl_enabled: true
consul_acl_default_policy: "deny"
docker_allow_privileged: false
nomad_raw_exec_enabled: false

# HashiCorp service versions for staging
consul_version: "{{ lookup('env', 'CONSUL_VERSION') | default('1.17.0', true) }}"
nomad_version: "{{ lookup('env', 'NOMAD_VERSION') | default('1.7.2', true) }}"
vault_version: "{{ lookup('env', 'VAULT_VERSION') | default('1.15.4', true) }}"

# Service configuration
consul_datacenter: dc1
consul_port: 8500
consul_log_level: WARN

nomad_datacenter: dc1
nomad_region: global
nomad_port: 4646
nomad_log_level: WARN

# Network configuration
consul_bind_addr: "{{ ansible_default_ipv4.address | default('127.0.0.1') }}"
nomad_bind_addr: "{{ ansible_default_ipv4.address | default('127.0.0.1') }}"

# Staging-specific settings
skip_security_hardening: false
enable_debug_logging: false

# Firewall settings for staging (more restrictive)
firewall_allow_ports:
  - "22/tcp"    # SSH
  - "80/tcp"    # HTTP
  - "443/tcp"   # HTTPS
  - "4646/tcp"  # Nomad HTTP
  - "8500/tcp"  # Consul HTTP API
  - "8200/tcp"  # Vault API

# TLS settings for staging
consul_encrypt_verify_incoming: true
consul_encrypt_verify_outgoing: true
nomad_tls_enabled: false  # Enable when certs are available