---
# Default variables for docker-installation role

# Docker version and repositories
docker_version: "24.0.*"
docker_compose_version: "2.21.0"
docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_apt_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_apt_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

# Docker daemon configuration
docker_daemon_config:
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"
  storage-driver: "overlay2"
  live-restore: true
  userland-proxy: false
  experimental: false
  metrics-addr: "127.0.0.1:9323"
  iptables: true
  ipv6: false

# Docker service configuration
docker_service_enabled: true
docker_service_state: "started"

# Users to add to docker group (empty for Phase 1 root-only)
docker_users: []

# Docker compose installation
install_docker_compose: true

# Security settings
docker_enable_content_trust: false  # Phase 1: basic setup
docker_enable_user_namespace: false  # Phase 1: basic setup

# Cleanup settings
docker_prune_enabled: true
docker_prune_schedule: "0 3 * * 0"  # Weekly at 3 AM Sunday