# Loki Configuration for HashiCorp Stack Log Aggregation
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info
  log_format: json
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s

# Common configuration shared between ingester and querier
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# Ingester configuration
ingester:
  # Lifecycler configuration
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
    
  # Chunk configuration
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0
  
  # WAL configuration  
  wal:
    enabled: true
    dir: /loki/wal
    checkpoint_duration: 5m
    flush_on_shutdown: true
    replay_memory_ceiling: 1GB

# Query configuration
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100
  cache_results: true
  max_retries: 5
  split_queries_by_interval: 15m
  align_queries_with_step: true

# Querier configuration  
querier:
  query_ingesters_within: 3h
  query_timeout: 1m
  tail_max_duration: 1h
  extra_query_delay: 0s
  
# Query frontend configuration
frontend:
  log_queries_longer_than: 5s
  downstream_url: http://127.0.0.1:3100
  compress_responses: true
  
frontend_worker:
  frontend_address: 127.0.0.1:9095
  grpc_client_config:
    max_send_msg_size: 104857600
    max_recv_msg_size: 104857600

# Schema configuration for HashiCorp services
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Storage configuration
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    shared_store: filesystem
    cache_ttl: 24h
    
  filesystem:
    directory: /loki/chunks

# Limits configuration for HashiCorp services
limits_config:
  # Ingestion limits
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_streams_per_user: 10000
  max_line_size: 256KB
  max_label_name_length: 1024
  max_label_value_length: 4096
  max_label_names_per_series: 30
  
  # Query limits
  max_entries_limit_per_query: 50000
  max_streams_matchers_per_query: 1000
  max_concurrent_tail_requests: 10
  
  # Global limits  
  max_global_streams_per_user: 5000
  max_chunks_per_query: 2000000
  max_query_length: 721h
  max_query_parallelism: 32
  
  # Retention period
  retention_period: 744h  # 31 days
  
  # Per-stream rate limiting
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 0s
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 1024
      ttl: 1h

# Table manager configuration
table_manager:
  retention_deletes_enabled: true
  retention_period: 744h  # 31 days

# Compactor configuration  
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Ruler configuration for alerting on HashiCorp logs
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true

# Analytics configuration
analytics:
  reporting_enabled: false

# Memberlist configuration (for future clustering)
memberlist:
  node_name: loki-single
  join_members:
    - loki-single:7946
  bind_port: 7946
  gossip_interval: 5s
  gossip_nodes: 3
  gossip_to_dead_time: 30s
  left_ingesters_timeout: 30s
  dead_node_reclaim_time: 0s
  compression_enabled: true

# Tracing configuration
tracing:
  enabled: false