---
# Production Inventory for HashiCorp Stack
# Based on proven patterns from existing repository

all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/cloudya_deploy
    consul_datacenter: dc1
    nomad_datacenter: dc1
    environment: production
    
consul_servers:
  hosts:
    consul-1:
      ansible_host: 10.0.1.10
      consul_node_id: consul-server-1
      consul_bootstrap_expect: 3
    consul-2:
      ansible_host: 10.0.1.11
      consul_node_id: consul-server-2
    consul-3:
      ansible_host: 10.0.1.12
      consul_node_id: consul-server-3
  vars:
    consul_server: true
    consul_ui: true
    consul_encrypt_key: "{{ vault_consul_encrypt_key }}"

nomad_servers:
  hosts:
    nomad-1:
      ansible_host: 10.0.1.20
      nomad_node_id: nomad-server-1
      nomad_bootstrap_expect: 3
    nomad-2:
      ansible_host: 10.0.1.21
      nomad_node_id: nomad-server-2
    nomad-3:
      ansible_host: 10.0.1.22
      nomad_node_id: nomad-server-3
  vars:
    nomad_server: true
    nomad_ui: true

nomad_clients:
  hosts:
    client-[1:5]:
      ansible_host: 10.0.2.[10:14]
  vars:
    nomad_client: true
    nomad_client_meta:
      rack: "{{ ansible_hostname.split('-')[-1] }}"
      zone: "{{ ansible_local.zone | default('a') }}"

vault_servers:
  hosts:
    vault-1:
      ansible_host: 10.0.1.30
      vault_node_id: vault-server-1
    vault-2:
      ansible_host: 10.0.1.31
      vault_node_id: vault-server-2
    vault-3:
      ansible_host: 10.0.1.32
      vault_node_id: vault-server-3
  vars:
    vault_server: true
    vault_ui: true
    vault_storage: consul