global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false
  debug: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
      middlewares:
        - compression@file
        - security-headers@file

  websecure:
    address: ":443"
    http:
      middlewares:
        - compression@file
        - security-headers@file
      tls:
        options: default

certificatesResolvers:
  letsencrypt:
    acme:
      httpChallenge:
        entryPoint: web
      email: admin@cloudya.net
      storage: /letsencrypt/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      keyType: EC256

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: cloudya
    watch: true
    pollInterval: "5s"
  
  file:
    directory: /etc/traefik/dynamic
    watch: true
    pollInterval: "5s"

# Enhanced logging
log:
  level: INFO
  format: json
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  format: json
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-599"
    retryAttempts: true
    minDuration: "10ms"
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep

# Metrics for monitoring
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    manualRouting: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# Tracing (optional)
tracing:
  jaeger:
    samplingType: const
    samplingParam: 1.0
    localAgentHostPort: "127.0.0.1:6831"

# Health check endpoint
ping:
  entryPoint: "web"

# Connection settings
serversTransport:
  insecureSkipVerify: false
  rootCAs:
    - /etc/ssl/certs/ca-certificates.crt
  maxIdleConnsPerHost: 42
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 30s
    idleConnTimeout: 90s

# Cluster configuration (if using multiple Traefik instances)
cluster:
  store: consul
  prefix: traefik