---
# Staging Inventory for Phase 1 Bootstrap
# Simplified single-node setup for testing

all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/cloudya_deploy
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    consul_datacenter: staging
    nomad_datacenter: staging
    environment: staging
    
    # Phase 1 Bootstrap - no Vault integration yet
    bootstrap_phase: 1
    vault_integration: false
    
consul_servers:
  hosts:
    staging-node:
      ansible_host: 10.0.10.10
      consul_node_id: consul-staging
      consul_bootstrap_expect: 1
  vars:
    consul_server: true
    consul_ui: true
    consul_bind_address: "127.0.0.1"  # Phase 1: localhost only
    consul_client_address: "127.0.0.1"
    
nomad_servers:
  hosts:
    staging-node:
      ansible_host: 10.0.10.10
      nomad_node_id: nomad-staging
      nomad_bootstrap_expect: 1
  vars:
    nomad_server: true
    nomad_ui: true
    nomad_client: true  # Combined server/client for staging
    # Phase 1: NO vault{} block

nomad_clients:
  hosts:
    staging-node:
      ansible_host: 10.0.10.10
  vars:
    nomad_client: true
    nomad_client_meta:
      rack: "1"
      zone: "staging"