---
- name: Configure UFW Firewall
  hosts: all
  become: yes
  
  tasks:
    - name: Reset UFW to defaults
      ufw:
        state: reset

    - name: Set UFW default policies
      ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      loop:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }
        - { direction: 'routed', policy: 'deny' }

    - name: Allow SSH (port 22)
      ufw:
        rule: allow
        port: '22'
        proto: tcp
        comment: "SSH access"

    - name: Allow HTTP (port 80)
      ufw:
        rule: allow
        port: '80'
        proto: tcp
        comment: "HTTP access"

    - name: Allow HTTPS (port 443)
      ufw:
        rule: allow
        port: '443'
        proto: tcp
        comment: "HTTPS access"

    - name: Allow localhost traffic
      ufw:
        rule: allow
        from_ip: '127.0.0.1'
        comment: "Localhost traffic"

    - name: Allow loopback interface
      ufw:
        rule: allow
        interface: lo
        direction: in

    - name: Allow loopback interface outbound
      ufw:
        rule: allow
        interface: lo
        direction: out

    - name: Enable UFW logging
      ufw:
        logging: 'on'

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Display UFW status
      command: ufw status verbose
      register: ufw_status
      changed_when: false

    - name: Show UFW status
      debug:
        var: ufw_status.stdout_lines